<a href="https://colab.research.google.com/github/Saurabh08281997/NLP/blob/main/Word_embedding_Techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Word Embedding Techniques using Embedding Layer in Keras

In [1]:
### Libraries USed Tensorflow> 2.0  and keras

In [2]:
!pip install tensorflow-gpu

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 511.7 MB 6.6 kB/s 
     |████████████████████████████████| 5.8 MB 55.7 MB/s 
     |████████████████████████████████| 438 kB 67.3 MB/s 
     |████████████████████████████████| 1.6 MB 54.8 MB/s 
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.8.0
    Uninstalling tensorflow-estimator-2.8.0:
      Successfully uninstalled tensorflow-estimator-2.8.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.8.0
    Uninstalling tensorboard-2.8.0:
      Successfully uninstalled tensorboard-2.8.0
  Attempting uninstall: keras
    Found existing installation: keras 2.8.0
    Uninstalling keras-2.8.0:
      Successfully uninstalled keras-2.8.0
  Attempting uninstall: gast
    Found existing installation: gast 0.5.3
    Uninstalling gast-0.5.3:
      Successfully uninstalled gast-0.

In [3]:
import tensorflow as tf
print(tf.__version__)

2.9.1


In [4]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### Vocabulary size
voc_size=500

#### One Hot Representation

In [8]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[395, 158, 211, 459], [395, 158, 211, 403], [395, 5, 211, 186], [362, 444, 193, 294, 196], [362, 444, 193, 294, 385], [333, 395, 345, 211, 392], [344, 491, 104, 294]]


### Word Embedding Represntation

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 395 158 211 459]
 [  0   0   0   0 395 158 211 403]
 [  0   0   0   0 395   5 211 186]
 [  0   0   0 362 444 193 294 196]
 [  0   0   0 362 444 193 294 385]
 [  0   0   0 333 395 345 211 392]
 [  0   0   0   0 344 491 104 294]]


In [12]:
## 10 feature dimesnions
dim=10


In [13]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [15]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 395, 158, 211, 459], dtype=int32)

In [16]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 73ms/step


array([[-0.01791962,  0.02841303, -0.02305583,  0.02572774, -0.0040531 ,
        -0.04357076, -0.04267012, -0.03945643, -0.02268144,  0.03864319],
       [-0.01791962,  0.02841303, -0.02305583,  0.02572774, -0.0040531 ,
        -0.04357076, -0.04267012, -0.03945643, -0.02268144,  0.03864319],
       [-0.01791962,  0.02841303, -0.02305583,  0.02572774, -0.0040531 ,
        -0.04357076, -0.04267012, -0.03945643, -0.02268144,  0.03864319],
       [-0.01791962,  0.02841303, -0.02305583,  0.02572774, -0.0040531 ,
        -0.04357076, -0.04267012, -0.03945643, -0.02268144,  0.03864319],
       [ 0.00407823, -0.00976623, -0.04336103,  0.0324139 ,  0.0351989 ,
        -0.01978337, -0.03287093, -0.02733984, -0.01718644,  0.01549977],
       [-0.01273983,  0.003294  , -0.00844391,  0.02276409,  0.03437206,
         0.03252831, -0.04494274,  0.00783353,  0.03872913, -0.04558892],
       [ 0.04533176, -0.02586664, -0.00403938,  0.02101089, -0.00255914,
         0.00538317, -0.02752211,  0.01933286

In [17]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 35ms/step
[[[-0.01791962  0.02841303 -0.02305583  0.02572774 -0.0040531
   -0.04357076 -0.04267012 -0.03945643 -0.02268144  0.03864319]
  [-0.01791962  0.02841303 -0.02305583  0.02572774 -0.0040531
   -0.04357076 -0.04267012 -0.03945643 -0.02268144  0.03864319]
  [-0.01791962  0.02841303 -0.02305583  0.02572774 -0.0040531
   -0.04357076 -0.04267012 -0.03945643 -0.02268144  0.03864319]
  [-0.01791962  0.02841303 -0.02305583  0.02572774 -0.0040531
   -0.04357076 -0.04267012 -0.03945643 -0.02268144  0.03864319]
  [ 0.00407823 -0.00976623 -0.04336103  0.0324139   0.0351989
   -0.01978337 -0.03287093 -0.02733984 -0.01718644  0.01549977]
  [-0.01273983  0.003294   -0.00844391  0.02276409  0.03437206
    0.03252831 -0.04494274  0.00783353  0.03872913 -0.04558892]
  [ 0.04533176 -0.02586664 -0.00403938  0.02101089 -0.00255914
    0.00538317 -0.02752211  0.01933286  0.03053052  0.00376844]
  [-0.03672664 -0.02508453  0.03800255 -0.00085698 -0.04976064
 

In [18]:
embedded_docs[0]

array([  0,   0,   0,   0, 395, 158, 211, 459], dtype=int32)

In [19]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 17ms/step
[[-0.01791962  0.02841303 -0.02305583  0.02572774 -0.0040531  -0.04357076
  -0.04267012 -0.03945643 -0.02268144  0.03864319]
 [-0.01791962  0.02841303 -0.02305583  0.02572774 -0.0040531  -0.04357076
  -0.04267012 -0.03945643 -0.02268144  0.03864319]
 [-0.01791962  0.02841303 -0.02305583  0.02572774 -0.0040531  -0.04357076
  -0.04267012 -0.03945643 -0.02268144  0.03864319]
 [-0.01791962  0.02841303 -0.02305583  0.02572774 -0.0040531  -0.04357076
  -0.04267012 -0.03945643 -0.02268144  0.03864319]
 [ 0.00407823 -0.00976623 -0.04336103  0.0324139   0.0351989  -0.01978337
  -0.03287093 -0.02733984 -0.01718644  0.01549977]
 [-0.01273983  0.003294   -0.00844391  0.02276409  0.03437206  0.03252831
  -0.04494274  0.00783353  0.03872913 -0.04558892]
 [ 0.04533176 -0.02586664 -0.00403938  0.02101089 -0.00255914  0.00538317
  -0.02752211  0.01933286  0.03053052  0.00376844]
 [-0.03672664 -0.02508453  0.03800255 -0.00085698 -0.04976064  0.04740309

In [20]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]